### ISSUE TITLE
The first object in a map fails to have a collider created

### ISSUE THREAD

**Issue by alanbaumgartner** [adrien-bon/bevy_ecs_tiled#64] opened 2024-12-14 22:12 UTC
Tested this on both main and dev branches.

Using one of the examples, the object with `id="4"` will not have a collider created but the subsequent two will.
https://github.com/adrien-bon/bevy_ecs_tiled/blob/9d63876bf82913188bfe03b969b08df25a1216d2/assets/multiple_layers_with_colliders.tmx#L4-L10

The problem is that the first time the event `TiledObjectCreated` is triggered, there may not be a `TiledPhysicsSettings` component.

These 2 observers both listen to that event, the first one will succeed in creating `TiledPhysicsSettings` while the second will short circuit. On every subsequent trigger, the first one is no-ops and the second creates the collider.
https://github.com/adrien-bon/bevy_ecs_tiled/blob/9d63876bf82913188bfe03b969b08df25a1216d2/src/physics/mod.rs#L99-L100

The simplest option may be to clone and re-trigger the event in the `default_physics_settings` observer.
https://github.com/adrien-bon/bevy_ecs_tiled/blob/9d63876bf82913188bfe03b969b08df25a1216d2/src/physics/mod.rs#L105-L118

Another option could be to remove `default_physics_settings` entirely and have `TiledPhysicsSettings` inserted here instead of returning. Or inserted somewhere prior to triggering `TiledObjectCreated` events.
https://github.com/adrien-bon/bevy_ecs_tiled/blob/9d63876bf82913188bfe03b969b08df25a1216d2/src/physics/mod.rs#L130-L132

**Comment by adrien-bon** [comment] 2024-12-14 22:26
Hey!
Thanks for the report.

Actually, I believe this is a typo: my bad for not catching it.
The `default_physics_settings<T>()` function should be triggered by a `TiledMapCreated` and not a `TiledObjectCreated`. By design, we should always have events from the map before events for objects / tiles.

I'll fix that

**Comment by adrien-bon** [comment] 2024-12-14 22:47
Fixed in `dev` branch: https://github.com/adrien-bon/bevy_ecs_tiled/commit/1ab998ba9d8982108e6ece7c4ad90525d61a4536

Official release "coming soon" :)

**Closed by adrien-bon** 2024-12-14 22:47 UTC
Labels: bug
